# Usar a imagem base do PostgreSQL
FROM postgres:15.8
RUN apt-get update && apt-get install -y postgresql-15-cron

# Expor a porta padrão do PostgreSQL
EXPOSE 5432

# Comando de inicialização padrão do container
CMD ["postgres"]